# This rule is not used by the project sample-external-issuer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the omega-issuer.omegahome.net.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: omega-external-issuer
    app.kubernetes.io/managed-by: kustomize
  name: omegaclusterissuer-editor-role
rules:
- apiGroups:
  - omega-issuer.omegahome.net
  resources:
  - omegaclusterissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - omega-issuer.omegahome.net
  resources:
  - omegaclusterissuers/status
  verbs:
  - get
