# This rule is not used by the project sample-external-issuer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to omega-issuer.omegahome.net resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: omega-external-issuer
    app.kubernetes.io/managed-by: kustomize
  name: omegaissuer-viewer-role
rules:
- apiGroups:
  - omega-issuer.omegahome.net
  resources:
  - omegaissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - omega-issuer.omegahome.net
  resources:
  - omegaissuers/status
  verbs:
  - get
