---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests/status
  verbs:
  - patch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/status
  verbs:
  - patch
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - omegaissuers.omega-issuer.omegahome.net/*
  - omegaclusterissuers.omega-issuer.omegahome.net/*
  resources:
  - signers
  verbs:
  - sign
- apiGroups:
  - omega-issuer.omegahome.net
  resources:
  - omegaissuers
  - omegaclusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - omega-issuer.omegahome.net
  resources:
  - omegaissuers/status
  - omegaclusterissuers/status
  verbs:
  - patch
