apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "omega-issuer.fullname" . }}-cert-manager-controller-approve:omega-issuer
  labels:
  {{- include "omega-issuer.labels" . | nindent 4 }}
rules:
- apiGroups:
  - cert-manager.io
  resourceNames:
  - omegaissuers.omega-issuer.omegahome.net/*
  - omegaclusterissuers.omega-issuer.omegahome.net/*
  resources:
  - signers
  verbs:
  - approve
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "omega-issuer.fullname" . }}-cert-manager-controller-approve:omega-issuer
  labels:
  {{- include "omega-issuer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "omega-issuer.fullname" . }}-cert-manager-controller-approve:omega-issuer'
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: '{{ .Release.Namespace }}'
